# Generated by Django 4.0 on 2022-06-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categori', models.CharField(max_length=50)),
                ('pname', models.CharField(max_length=50)),
                ('pid', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('ptype', models.CharField(max_length=50)),
            ],
        ),
    ]
