# Generated by Django 4.0 on 2022-06-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='pname',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
