# Generated by Django 4.0 on 2022-06-17 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0005_cart_pname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='pname',
        ),
        migrations.AddField(
            model_name='cart',
            name='cby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='buyer.user'),
            preserve_default=False,
        ),
    ]
