# Generated by Django 3.2.13 on 2022-06-18 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0006_remove_cart_pname_cart_cby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cby',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='pid',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='pqty',
        ),
        migrations.AddField(
            model_name='cart',
            name='address',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='cart',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='cart',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
