# Generated by Django 3.2.13 on 2022-06-18 09:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0007_auto_20220618_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='entity_id',
            field=models.CharField(blank=True, default=uuid.UUID('0f0ce6d4-088d-4957-b2f8-698f008a4a9f'), max_length=100, null=True, unique=True),
        ),
    ]
