# Generated by Django 3.2.13 on 2022-06-18 09:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0008_cart_entity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='entity_id',
            field=models.CharField(blank=True, default=uuid.UUID('63a35007-ed6a-4531-82d5-da912273e008'), max_length=100, null=True, unique=True),
        ),
    ]
