# Generated by Django 3.2.13 on 2022-06-18 09:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0009_alter_cart_entity_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='entity_id',
        ),
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.CharField(blank=True, default=uuid.UUID('43bf81e1-3472-424c-bbb8-d060a4c6484a'), max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
