# Generated by Django 3.2.13 on 2022-06-18 09:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0010_auto_20220618_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.CharField(blank=True, default=uuid.UUID('d8edc059-24fd-44c6-96be-1ba3d3ddaa83'), max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
