# Generated by Django 3.2.13 on 2022-06-18 09:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0011_alter_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.CharField(blank=True, default=uuid.UUID('8ecec9bf-c4e2-4255-9524-6a5b762d7346'), max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
