# Generated by Django 4.0 on 2022-06-18 15:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0014_auto_20220618_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.CharField(blank=True, default=uuid.UUID('92ed734c-73bc-4839-b771-e5af8d83c7de'), max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
