# Generated by Django 4.0 on 2022-06-18 16:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0015_alter_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.CharField(blank=True, default=uuid.UUID('83510114-345b-46a9-89fd-526351743820'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
