# Generated by Django 4.0 on 2022-06-18 16:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0017_remove_cart_id_cart_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='cid',
            field=models.CharField(default=uuid.UUID('c70872c6-07a4-4644-a043-b3080d3545c4'), max_length=100),
        ),
    ]
