# Generated by Django 3.2.13 on 2022-06-19 06:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0018_cart_id_alter_cart_cid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categori',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='cart',
            name='cid',
            field=models.CharField(default=uuid.UUID('e1cabff3-7c36-4868-9458-f333085fff08'), max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(default=uuid.UUID('086c6453-3b25-4314-969d-bbf7d484c78c'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
