# Generated by Django 4.0 on 2022-06-19 10:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0019_auto_20220619_0632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='address',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='phone',
        ),
        migrations.AddField(
            model_name='product',
            name='pdes',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cid',
            field=models.CharField(default=uuid.UUID('ca156687-3dab-424a-bc1c-9a3a63255ebd'), max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(default=uuid.UUID('4d71a323-d59c-4a4a-be60-b5da18db2d3a'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
