# Generated by Django 4.0 on 2022-06-19 10:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0020_category_remove_cart_address_remove_cart_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cid',
            field=models.CharField(default=uuid.UUID('ea978bf3-31a9-4594-a7da-32a029b50357'), max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='buyer.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(default=uuid.UUID('f9fa6bd9-48be-43d4-b1c5-7929387e0f65'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
