# Generated by Django 4.0 on 2022-06-19 10:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0022_remove_product_pid_product_id_alter_cart_cid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AddField(
            model_name='product',
            name='pid',
            field=models.CharField(default=uuid.UUID('d27ad895-04e9-4794-b487-9dee1ebdff37'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cid',
            field=models.CharField(default=uuid.UUID('d2406eae-3553-4273-89c2-d4b87f58e94e'), max_length=100),
        ),
    ]
