# Generated by Django 4.0 on 2022-06-19 10:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0023_remove_product_category_remove_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cid',
            field=models.CharField(default=uuid.UUID('04992ad6-4f69-459a-971d-fb12d0b06ec7'), max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(default=uuid.UUID('cfac7a44-6d39-4741-a0ff-ee4cac8da770'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
