# Generated by Django 4.0 on 2022-06-19 10:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0024_alter_cart_cid_alter_product_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cid',
            field=models.CharField(default=uuid.UUID('6ca3c502-738e-41f4-ab55-25f69250c435'), max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(default=uuid.UUID('a9a0d335-d553-4342-b4ca-1df958f69cd1'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
