# Generated by Django 4.0 on 2022-06-19 10:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0025_alter_cart_cid_alter_product_pid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categoriy',
        ),
        migrations.AlterField(
            model_name='cart',
            name='cid',
            field=models.CharField(default=uuid.UUID('f968cb33-8d6d-44e4-9e91-f66f51f72900'), max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(default=uuid.UUID('0a317292-82b4-4d9e-ad2d-e5cc3c54a0c9'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
