# Generated by Django 4.0 on 2022-06-19 11:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0026_rename_category_categoriy_alter_cart_cid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cid',
            field=models.CharField(default=uuid.UUID('eac111dc-ad6c-4a70-8dd3-03e29e69ae79'), max_length=100),
        ),
        migrations.AlterField(
            model_name='categoriy',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(default=uuid.UUID('db59957f-e6dc-4fdd-bb38-28af8873d7ed'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
