# Generated by Django 3.2.13 on 2022-06-19 12:22

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0027_alter_cart_cid_alter_categoriy_id_alter_product_pid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoriy',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='id',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cid',
            field=models.CharField(default=uuid.UUID('1eb08bf3-6a9e-4f95-824a-13f2a487c882'), max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(default=uuid.UUID('f5eed901-3dca-4127-b4d2-c9c25346565c'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
