# Generated by Django 3.2.13 on 2022-06-19 12:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0030_auto_20220619_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pdes',
        ),
        migrations.AlterField(
            model_name='cart',
            name='cid',
            field=models.CharField(default=uuid.UUID('a2f8cfeb-f40f-4817-9fd4-effa7142663e'), max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(default=uuid.UUID('a8eedf75-0a6b-4fe1-9b2f-681ef2abf7c5'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(default='', max_length=200),
        ),
    ]
