# Generated by Django 4.0 on 2022-06-19 13:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0032_auto_20220619_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='ptype',
        ),
        migrations.AddField(
            model_name='product',
            name='pdes',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cid',
            field=models.CharField(default=uuid.UUID('96fc6ead-a8ca-4211-a089-85affaf84fdb'), max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(default=uuid.UUID('86967729-c2a8-47a4-ae45-649693c4b430'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
