# Generated by Django 3.2.13 on 2022-06-20 10:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0033_rename_type_product_ptype_product_pdes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cid',
            field=models.CharField(default=uuid.UUID('a981d8a5-93a7-435c-8b83-8429a38460a1'), max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='ipic',
            field=models.ImageField(default='avatar.jpg', upload_to='product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(default=uuid.UUID('b6c394f3-77a4-40c5-8bfc-080cc7bd0e07'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
