# Generated by Django 3.2.13 on 2022-06-20 11:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0034_auto_20220620_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cid',
            field=models.CharField(default=uuid.UUID('8377d66f-6f37-4fa5-a801-968c173b5938'), max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(default=uuid.UUID('676d9a26-2b26-4d57-94b2-d520cb7b612a'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
