# Generated by Django 3.2.13 on 2022-06-20 14:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0035_auto_20220620_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ipic',
            field=models.ImageField(default='avatar.jpg', upload_to='category'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cid',
            field=models.CharField(default=uuid.UUID('46dcefcf-13e6-4510-a258-719d18240897'), max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(default=uuid.UUID('20d8fd25-3501-4433-bbe5-9a84a02f1cd2'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(default=uuid.UUID('57a5fe7b-933f-4e7f-a981-46053041cf87'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
