# Generated by Django 3.2.13 on 2022-06-20 15:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0036_auto_20220620_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cid',
            field=models.CharField(default=uuid.UUID('4f4b6b21-b060-479f-8490-68d7c8e74161'), max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(default=uuid.UUID('bf7559d2-49b3-49dc-89d3-1cec3d7bc5e9'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='ipic',
            field=models.ImageField(default='avatar.jpg', upload_to='media/category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ipic',
            field=models.ImageField(default='avatar.jpg', upload_to='media/product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(default=uuid.UUID('866ae03a-13cb-41af-b3d5-5fc3525c52fb'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
