# Generated by Django 3.2.13 on 2022-06-21 09:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0037_auto_20220620_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cid',
            field=models.CharField(default=uuid.UUID('42503154-72bf-4cae-b9ad-2f1758ae4b74'), max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(default=uuid.UUID('e4a37153-589c-49f5-a348-3ad8b4800dc2'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(default=uuid.UUID('353e629d-f4b8-46d8-81b0-706053d88747'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
