# Generated by Django 4.0 on 2022-06-30 16:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0040_auto_20220621_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.CharField(default=uuid.UUID('c90f97c0-5d7b-42b2-8e08-3301522fe7cb'), max_length=100, primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.CharField(default=uuid.UUID('d10b0e83-4c4a-48b0-9bca-9552e5f6a2bc'), max_length=100, primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='cid',
            field=models.CharField(default=uuid.UUID('4aa7178d-cc82-4bf8-8b6e-f97dbd79dfb9'), max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(default=uuid.UUID('f5044709-2b7d-488a-989a-a2a46fc9cd5e'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(default=uuid.UUID('daecf00b-a427-4277-b0fa-a8c56e73582e'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.colors'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.size'),
        ),
    ]
