# Generated by Django 4.0 on 2022-06-30 16:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0041_colors_size_alter_cart_cid_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cid',
            field=models.CharField(default=uuid.UUID('0910e8e2-92ab-4774-8221-09b9959070bc'), max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(default=uuid.UUID('57fea100-bb65-4535-8d91-f95342074922'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='colors',
            name='id',
            field=models.CharField(default=uuid.UUID('b5652084-559b-4d8b-98c1-3bb43af95926'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(default=uuid.UUID('a9e83005-ade7-401c-a1db-8b49e70af51e'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='size',
            name='id',
            field=models.CharField(default=uuid.UUID('d6139abc-cf54-4a88-a5bd-9da8df0bfc35'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
